dist: xenial
language: python

stages:
  - test
  - deploy

install:
  - pip install -r dev-requirements.txt --extra-index https://${ART_API_USER}:${ART_API_KEY}@eu.artifactory.swg-devops.com/artifactory/api/pypi/sec-iam-isam-devops-team-pypi-local/simple

script:
  - sh ./.tests/import_test.sh

jobs:
  include:
    - stage: test
      script: 
        - sh ./.tests/import_test.sh
        - sh ./.tests/unit_test.sh
      python:
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10-dev"
    - stage: deploy
      script: 
        - ./.deploy.sh
      python:
        - "3.9"
      if: branch = stable
