apiVersion: batch/v1 
kind: Job 
metadata:
  name: isvaconfigurator
  labels:
    app: isvaconfigurator
spec:
  backoffLimit: 0
  template: 
    metadata:
      labels:
        app: isvaconfigurator
    spec:
      imagePullSecrets:
        - name: isva-config-login
      containers:
        - name: isvaconfigurator
          image: sec-iam-isam-devops-team-docker-local.artifactory.swg-devops.com/isva-configurator:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /usr/app/config
              name: kubeconfigvolume
          env:
            - name: MGMT_BASE_URL
              value: 'https://168.1.30.85:30543'
            - name: MGMT_PASSWORD
              value: 'admin'
            - name: KUBECONFIG
              value: '/usr/app/config/kubeconfig.yaml'
            - name: ISVA_CONFIGURATION_YAML
              value: '/usr/app/config/config.yaml'
      volumes:
        - name: kubeconfigvolume
          configMap:
            name: kubeconfig
      restartPolicy: Never
